### ISSUE TITLE
Doesn't localize format strings correctly

### ISSUE THREAD

**Issue by mulle-nat** [nanaimostudio/Xcode-Quick-Localization#11]
``@"print %@"`` gets turned into ``"print %" =  "print %"``

**Comment by caoer** [comment]
I'm able to convert `@"print %@"` correctly. Can you give more context?

**Comment by mulle-nat** [comment]
I just tried this. I create a new OS X app in Xcode 6.2. I add a file `Localizable.strings`. Then I set this to the localizable file with **Refactor / Change Localizable File**

Then I wrote:
```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
   NSLog( @"Here is a \"%@\" and a %@", @"foo", @"bar");
}
```
When I select the format string and choose **Refactor / Extract Localizable String** it doesn't work correctly for me. I hope this helps somewhat.

**Comment by caoer** [comment]
@mulle-nat fixed, thanks.
