### ISSUE TITLE
Only convert the string under cursor

### ISSUE THREAD

**Issue by xhacker** [nanaimostudio/Xcode-Quick-Localization#12]
Currently QuickLocalization converts strings in the current line, which is not ideal in some cases.

**Comment by caoer** [comment]
@xhacker you can select multiple lines as well.

**Comment by xhacker** [comment]
Sorry I wasn't clear, I mean sometimes there are more than one strings in one line, but I only want to convert one of them.

**Comment by caoer** [comment]
gotcha!

right now it does not have this feature, I will look into it when I'm free up.

**Comment by xhacker** [comment]
Cool, thanks!

**Comment by caoer** [comment]
@xhacker finally I got a chance to take care of this issue. now it can support selected text!!! I also get it a new setting panel, check it out please, let me know if you have any feedback. :1234:

**Comment by xhacker** [comment]
Worked very well for me, thank you!
