### ISSUE TITLE
7.1.1 Crash

### ISSUE THREAD

**Issue by patrickbgit** [nanaimostudio/Xcode-Quick-Localization#21]
Thanks for a fantastic plugin! Seems it crashes with the latest Xcode.
Occurs when using the keyboard shortcut to localise.

Version:         7.1.1 (9081)
Build Version:   5

Trace:
  97  start + 1 (libdyld.dylib + 13769) [0x7fff853b75c9]
  97  NSApplicationMain + 1832 (AppKit + 12868) [0x7fff855f9244]
  97  -[NSApplication run] + 711 (AppKit + 551784) [0x7fff8567cb68]
  97  -[IDEApplication sendEvent:] + 688 (IDEKit + 105394) [0x1047d9bb2]
  97  -[NSMenu performKeyEquivalent:] + 359 (AppKit + 2439341) [0x7fff858498ad]
  97  _os_activity_initiate + 75 (libsystem_trace.dylib + 3287) [0x7fff85254cd7]
  97  -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114 (AppKit + 2443644) [0x7fff8584a97c]
  97  -[NSMenuItem _corePerformAction] + 382 (AppKit + 2444366) [0x7fff8584ac4e]
  97  -[DVTApplication sendAction:to:from:] + 335 (DVTKit + 51239) [0x103a36827]
  97  DVTInvokeWithFailureHint + 83 (DVTFoundation + 2263468) [0x10358d9ac]
  97  __37-[DVTApplication sendAction:to:from:]_block_invoke + 379 (DVTKit + 1290233) [0x103b64ff9]
  97  -[NSApplication sendAction:to:from:] + 452 (AppKit + 2444977) [0x7fff8584aeb1]
  97  _os_activity_initiate + 75 (libsystem_trace.dylib + 3287) [0x7fff85254cd7]
  97  -[QuickLocalization quickLocalization:] + 383 (QuickLocalization.m:96,13 in QuickLocalization + 7918) [0x11199eeee]
  97  -[QuickLocalization replaceTextInRange:textView:] + 692 (QuickLocalization.m:123,39 in QuickLocalization + 8653) [0x11199f1cd]
  17  objc_msgSend + 138 (libobjc.A.dylib + 4426) [0x7fff8a39b14a] (running)

**Comment by caoer** [comment]
hi @patrickbgit  this issue is fixed in 2616d59a64c6d85ed4b35ece6ffb6a92a3d1567a

thanks for the report :+1:

**Comment by patrickbgit** [comment]
Thanks so much :]
