### ISSUE TITLE
Doesn't support Swift?

### ISSUE THREAD

**Issue by Francescu** [nanaimostudio/Xcode-Quick-Localization#4]
It seems that the plugin doesn't support Swift

**Comment by Jusung** [comment]
I've updated some code to make compatible with Swift.
Here is the link of it.(https://github.com/Jusung/Xcode-Quick-Localization)

**Comment by caoer** [comment]
@Francescu @Jusung 
added swift support in 8c02033fc6339131175d2b3f6dc37446e4736799, enjoy.

**Comment by Jusung** [comment]
Cool! @caoer

**Comment by Francescu** [comment]
Thanks!
