### ISSUE TITLE
Add option to use nil as the comment

### ISSUE THREAD

**Issue by lgauthier** [nanaimostudio/Xcode-Quick-Localization#6]
Hey, this is a pretty awesome plugin, but my only gripe is that the comment argument is also replaced with the original string. In a lot of cases, the comment argument isn't really necessary such as NSLocalizedString(@"Ok", nil).

It would be cool if there was an option in the Xcode menu to have it use nil as the comment instead of the original string. Another possibility is to make the comment "<#Comment#>" so the developer can easily tab through each localized string to add the comment describing the context of the string.

I've never worked on an Xcode plugin before, but if you like the idea, I might be able to make the update and send you a pull request if I find the time.

**Comment by caoer** [comment]
@lgauthier the idea of using tab complete comment is pretty cool! I'm tied up on other things right now, but I will look into implement it soon. thanks for the PR!. :+1:

**Comment by caoer** [comment]
94522b6c10674d7119d6a24d17382f0c3b60e695
